### ISSUE TITLE
Search is not being displayed

### ISSUE THREAD

**Issue by aebian** [PascalKleindienst/october-blogsearch-extension#4]
Live Link: https://beta.aebian.org/stories/
Code: https://gist.github.com/Aebian/13b2389a19e749f140ec

For some reason my search is not getting displayed. Do I need to add css code first?
I also cleared the Application Cache via sudo php artisan cache:clear

Kind Regards,

A.

**Comment by aebian** [comment]
sorry messed up my code, works now thanks for the plugin!

**Comment by PascalKleindienst** [comment]
Hi,

this is strange. You don't have to use any CSS in order to see the form. 
I tested your markup and it works fine for me. 

Could you enable the debug mode and test if it works without the {% partial 'stories/blogCategories.htm' %} _(don't forget to clear the cache before!)_

## 

Good to hear that it works now :smile:
